name: sputnik_ui
description: UI layer of Sputnik Messenger
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  url_launcher: ^5.0.3
  intl: ^0.15.8
  tuple: ^1.0.2
  flutter_cache_manager: ^0.3.2
  audioplayers: ^0.13.1
  flutter_html: ^0.10.1
  multi_image_picker: ^4.3.3
  flutter_redux: ^0.5.3
  flutter_udid: ^1.0.0
  downloads_path_provider: ^0.1.0
  sputnik_matrix_sdk:
    path: ../sputnik_matrix_sdk
  sputnik_audio_recorder:
    path: ../sputnik_audio_recorder
  flutter:
    sdk: flutter


dependency_overrides:
  path_provider: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
